apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: chat4u-app
        image: chat4u_app:v4
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        ports:
        - containerPort: 5000
        env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: APP_NAME